INSERT INTO PARAMETER(NAME) VALUES('Powtórzenia');
INSERT INTO PARAMETER(NAME) VALUES('Czas');
INSERT INTO PARAMETER(NAME) VALUES('Dystans');
INSERT INTO PARAMETER(NAME) VALUES('Kalorie spalane');
INSERT INTO PARAMETER(NAME) VALUES('Obciążenie');