
INSERT INTO USER_ACCOUNT (LOGIN, PASSWORD, DATE_REGISTERED, LAST_SEEN, EMAIL, ACCOUNT_ACTIVE, NAME, SURNAME, HEIGHT, WEIGHT) VALUES
('Marcus', '$2a$10$3/7x.Gk5teL/CxbIHFMUOuAKWjTGfSI3spipholfZTy.uTgr6oQDK', '2008-01-01', '2010-01-01', 'swedish@wp.eu', TRUE, 'Marc', 'Nacht', 189, 85);
INSERT INTO USER_ACCOUNT (LOGIN, PASSWORD, DATE_REGISTERED, LAST_SEEN, EMAIL, ACCOUNT_ACTIVE, NAME, SURNAME, HEIGHT, WEIGHT) VALUES
('user', 'user', '2008-01-01', '2010-01-01', 'user@wp.eu', TRUE, 'user', 'user', 178, 72);
INSERT INTO USER_ACCOUNT (LOGIN, PASSWORD, DATE_REGISTERED, LAST_SEEN, EMAIL, ACCOUNT_ACTIVE, NAME, SURNAME, HEIGHT, WEIGHT) VALUES
('test', '$2a$10$3/7x.Gk5teL/CxbIHFMUOuAKWjTGfSI3spipholfZTy.uTgr6oQDK', null, null, 'aplikacjatreningowa@gmail.com', TRUE, 'test', 'user', 192, 102);

/* Hasło - useruseruser */
